services:
  - type: web
    name: myfreedom
    env: php
    buildCommand: |
      composer install
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
